name: Build and deploy lagfest-signup azure function

on:
  workflow_dispatch:
  push:
    paths:
      - "api/lagfest-signup/**"
      - ".github/workflows/function-upload-signup.yaml"
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  PYTHON_VERSION: "3.10"
  AZURE_FUNCTION_APP_NAME: "ruut-backend-function-app"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        working-directory: api/lagfest-signup/
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: lagfest-signup
          path: api/lagfest-signup/

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: lagfest-signup
          path: .

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{env.AZURE_FUNCTION_APP_NAME}}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_APP_FUNCTION_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
